### ISSUE TITLE
Show images in mail messages

### ISSUE THREAD

**Issue by billba** [johnshew/GraphDashboard#9]

**Comment by johnshew** [comment]
I just sent you an email with data info on how to do this.

From Richard diZerega: for embedded Images – the images are stored as attachments on the message. This is a little confusing because the hasAttachments attribute could be false if only images are embedded. However, you can get to them as follows:

https://graph.microsoft.com/v1.0/me/messages/SOME_MESSAGE_ID/attachments

Where the contentId of the attachment will be equal to the GUID referenced in the href in the HTML body.

**Comment by billba** [comment]
fixed in Alpha 2
